name: Build

on:
  pull_request:
    branches: ["master", "dev"]

jobs:
  build-ios:
    name: Build on iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
